[network_config]


[DDP]
world_size = 2   # number of available gpus

[optimizer]
lr = 1e-3

[loss]
loss_func = 'hybrid'

[listener]
listener_sr = 16000

[FFT]
n_fft = 512
hop_length = 256
win_length = 512

[train_dataset]
train_folder = '/home/data1/DNSdatasets/train'
shuffle = false
num_tot = 0
wav_len = 0

[train_dataloader]
batch_size = 12
num_workers = 4
drop_last = true
pin_memory = true

[validation_dataset]
train_folder = '/home/data1/DNSdatasets/val'
shuffle = false
num_tot = 0
wav_len = 0

[validation_dataloader]
batch_size = 1
num_workers = 4
pin_memory = true

[trainer]
epochs = 120
save_checkpoint_interval = 1
clip_grad_norm_value = 3.0
exp_path = './exp_dpcrn/'
resume = false
resume_datetime = ''
resume_step = 0
